openapi: 3.0.0
info:
  title: Mosaic-Payment-API
  version: '1.0'
  description: Set of APIs expose throgh mosaic payment service
  contact:
    name: Mosaic Payment
servers:
  - url: 'http://localhost:8080'
paths:
  /v1/payment:
    post:
      summary: Make payments
      tags: []
      responses:
        '200':
          description: OK - Payment Succeeded!
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  id:
                    type: string
                    minLength: 1
                  create_time:
                    type: string
                    minLength: 1
                  update_time:
                    type: string
                    minLength: 1
                  state:
                    type: string
                    minLength: 1
                  intent:
                    type: string
                    minLength: 1
                  payment_method:
                    type: string
                    minLength: 1
                  amount:
                    type: string
                    minLength: 1
                  currency:
                    type: string
                    minLength: 1
                  details:
                    type: object
                    properties:
                      subtotal:
                        type: string
                        minLength: 1
                      tax:
                        type: string
                        minLength: 1
                      shipping:
                        type: string
                        minLength: 1
                    required:
                      - subtotal
                      - tax
                      - shipping
                  description:
                    type: string
                    minLength: 1
                required:
                  - id
                  - create_time
                  - update_time
                  - state
                  - intent
                  - payment_method
                  - amount
                  - currency
                  - details
                  - description
                x-examples:
                  example-1:
                    id: PAY-0US81985GW1191216KOY7OXA
                    create_time: '2017-06-30T23:48:44Z'
                    update_time: '2017-06-30T23:49:27Z'
                    state: APPROVED
                    intent: order
                    payment_method: paypal
                    amount: '41.15'
                    currency: USD
                    details:
                      subtotal: '30.00'
                      tax: '1.15'
                      shipping: '10.00'
                    description: The payment transaction description.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  orderID:
                    type: string
                    minLength: 1
                  state:
                    type: string
                    minLength: 1
                  intent:
                    type: string
                    minLength: 1
                  description:
                    type: string
                    minLength: 1
                required:
                  - orderID
                  - state
                  - intent
                  - description
                x-examples:
                  example-1:
                    orderID: CANB0564
                    state: INVALID_REQUEST
                    intent: order
                    description: The payment request fileds mah have invalid values.
      operationId: post-v1-payment
      description: End point which use to make a payment
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                orderID:
                  type: string
                  minLength: 1
                intent:
                  type: string
                  minLength: 1
                payment_method:
                  type: string
                  minLength: 1
                total:
                  type: string
                  minLength: 1
                currency:
                  type: string
                  minLength: 1
                description:
                  type: string
                  minLength: 1
                invoice_number:
                  type: string
                  minLength: 1
                shipping_address:
                  type: object
                  properties:
                    recipient_name:
                      type: string
                      minLength: 1
                    line1:
                      type: string
                      minLength: 1
                    line2:
                      type: string
                      minLength: 1
                    city:
                      type: string
                      minLength: 1
                    country_code:
                      type: string
                      minLength: 1
                    postal_code:
                      type: string
                      minLength: 1
                    phone:
                      type: string
                      minLength: 1
                    state:
                      type: string
                      minLength: 1
                  required:
                    - recipient_name
                    - line1
                    - line2
                    - city
                    - country_code
                    - postal_code
                    - phone
                    - state
                note_to_payer:
                  type: string
                  minLength: 1
                redirect_urls:
                  type: object
                  properties:
                    return_url:
                      type: string
                      minLength: 1
                    cancel_url:
                      type: string
                      minLength: 1
                  required:
                    - return_url
                    - cancel_url
              required:
                - orderID
                - intent
                - payment_method
                - total
                - currency
                - description
                - invoice_number
                - shipping_address
                - note_to_payer
                - redirect_urls
              x-examples:
                example-1:
                  orderID: CANB0564
                  intent: sale
                  payment_method: paypal
                  total: '30.11'
                  currency: USD
                  description: The payment transaction description.
                  invoice_number: '48787589673'
                  shipping_address:
                    recipient_name: Brian Robinson
                    line1: 4th Floor
                    line2: 'Unit #34'
                    city: San Jose
                    country_code: US
                    postal_code: '95131'
                    phone: '011862212345678'
                    state: CA
                  note_to_payer: Contact us for any questions on your order.
                  redirect_urls:
                    return_url: 'https://example.com/return'
                    cancel_url: 'https://example.com/cancel'
        description: Request payload to make payment
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      type: http
      scheme: basic
